### ISSUE TITLE
USER STORY: Product List

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#1]
As a **site user** I can **view a list of products** so that **I can get an overview of them and select one to purchase**

### Acceptance Criteria

- [ ] Product card containing image, title, price
- [ ] Card links out to product detail page

### Tasks

- [ ] Design product card
- [ ] Create product card
- [ ] Use product list in database to make product list on page
