### ISSUE TITLE
USER STORY: Select Product Quantity

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#10]
As a **site user** I can **select the quantity of a product for my order** so that **I can quickly order multiple of an item**

### Acceptance Criteria

- [ ] Quantity selector on product detail page
- [ ] Cannot select less than one for quantity
- [ ] Selected quantity is added to cart and price is updated accordingly

### Tasks

- [ ] Create quantity selector on product detail page
- [ ] Disable selecting less than one
- [ ] Add correct amount to cart when selected
