### ISSUE TITLE
USER STORY: View Cart

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#11]
As a **site user** I can **view my cart** so that **I can check what I am ordering and see the total price**

### Acceptance Criteria

- [x] View all products in their own line in cart
- [x] View price for each product
- [x] View total price in cart

### Tasks

- [x] Create cart page
- [x] Link cart icon to cart page
- [x] Display each product clearly in cart
- [x] Show each product cost
- [x] Show total cost
