### ISSUE TITLE
USER STORY: Edit Cart

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#12]
As a **site user** I can **edit my cart** so that **I can  quickly edit product quantities or remove items I do not want to order**

### Acceptance Criteria

- [x] Remove products from cart
- [x] Edit quantities in cart
- [x] Prices update when quantities update

### Tasks

- [x] Add quantity selector to cart products
- [x] Add remove item button to products
- [x] Update prices when changes are made
