### ISSUE TITLE
USER STORY: Payment Information

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#13]
As a **site user** I can **easily and securely enter my payment information** so that **I can order with ease and confidence**

### Acceptance Criteria

- [ ] Simple form for payment information
- [ ] Inform user how payment information is used and if it is saved
- [ ] Display stripe logo to instill confidence in security

### Tasks

- [ ] Create payment information form
- [ ] Take submitted information to handle payment
- [ ] Add policies to inform user about how their info is used
