### ISSUE TITLE
USER STORY: Order Confirmation

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#14]
As a **site user** I can **see an order confirmation** so that **I can be sure my order was made without issue**

### Acceptance Criteria

- [x] Order confirmation message on site
- [x] Order confirmation email
- [x] Error message incase of problems

### Tasks

- [x] Create order confirmation message for finished orders
- [x] Email order confirmations on finished orders
- [x] Display error message detailing problems if any
