### ISSUE TITLE
USER STORY: Add New Products

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#15]
As a **site admin** I can **add new products** so that **I can keep my site catalogue up to date with what we have**

### Acceptance Criteria

- [ ] Add product outside of admin
- [ ] Add all information needed
- [ ] Add product page cannot be accessed by anyone other than admin

### Tasks

- [ ] Create add product form
- [ ] Create add product page with form
- [ ] Use information submitted with form to create new product in database
- [ ] Secure page to only be accesible by admin users
