### ISSUE TITLE
USER STORY: Edit Products

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#16]
As a **site admin** I can **edit existing products** so that **I can keep my product offers up to date**

### Acceptance Criteria

- [x] Edit products outside of admin panel
- [x] Only accessible to admin users

### Tasks

- [x] Create edit product form
- [x] Create edit product page
- [x] Update database with new information on submission
- [x] Secure page from non admin users
