### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#17]
As a **site admin** I can **delete products** so that **I can remove products we no longer offer**

### Acceptance Criteria

- [ ] Can delete products from outside admin panel
- [ ] Deleted products are removed from  database
- [ ] Only accessible to admin users
- [ ] Confirmation before deletion

### Tasks

- [ ] Create delete button for products
- [ ] Create confirmation popup before deleting
- [ ] Remove items fully from database
