### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#18]
As a **site user** I can **sign up for a newsletter** so that **I can be kept up to date with new products and offers from the store**

### Acceptance Criteria

- [ ] Sign up with email
- [ ] Inform users of email frequency and content

### Tasks

- [ ] Create form to take user email
- [ ] Use submitted email to create newsletter list
- [ ] Use mailchimp to send out mass emails
