### ISSUE TITLE
USER STORY: Product Detail Page

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#2]
As a **site user** I can **see a product detail page** so that **I can see more information on products I'm interested in**

### Acceptance Criteria

- [ ] Product card links to product detail
- [ ] All products have their own  page
- [ ] Product can be added to cart from product detail page
- [ ] Quantity can be selected on product detail

### Tasks

- [ ] Create product detail page
- [ ] Add function to add product to cart
- [ ] Add selector for product quantity
