### ISSUE TITLE
USER STORY: Product Availability

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#20]
As a **site user** I can **see an out of stock badge** so that **I can easily identify items that are not currently in stock**

### Acceptance Criteria

- [x] Out of stock badge clearly showing item as unavailable for order
- [x] Unavailable items cannot be ordered

### Tasks

- [x] Create out of stock badge
- [x] Disable ordering items without stock
