### ISSUE TITLE
USER STORY: SEO Features

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#21]
As a **site admin** I can **implement good SEO features** so that **my store ranks highly on google search results**

### Acceptance Criteria

- [ ] Meta head tags
- [ ] Accessibility attributes
- [ ] Rel attributes
- [ ] robots.txt
- [ ] Sitemap

### Tasks

- [ ] Add keyword meta tag
- [ ] Use accessibility attributes where appropriate
- [ ] Create a robots.txt file
- [ ] Create a sitemap
