### ISSUE TITLE
USER STORY: Facebook Page

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#22]
As a **site admin** I can **create a business facebook page** so that **I can increase my brand presence and user relationship**

### Acceptance Criteria

- [ ] Facebook page for business
- [ ] Link facebook to website

### Tasks

- [ ] Create facebook page for website
- [ ] Link site in footer/contact page
- [ ] Take screenshots of facebook page
