### ISSUE TITLE
USER STORY: Google Signup

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#23]
As a **site user** I can **sign up with my google account** so that **I can signup and login quickly and easily**

### Acceptance Criteria

- [ ] Register with google
- [ ] Sign in with google

### Tasks

- [ ] Install django all auth
- [ ] Use django social account features to add google sign in functionality

**Comment by alexkavanagh-dev** [comment]
This feature will not be added in the final version.
