### ISSUE TITLE
USER STORY: Wishlist Products

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#24]
As a **registered user** I can **save items to a wishlist** so that **I can come back and order them in future and check for sales**

### Acceptance Criteria

- [ ] Wishlist button
- [ ] Wishlist on profile page
- [ ] See current prices on wishlist
- [ ] Add to cart from wishlist

### Tasks

- [ ] Create wishlist button
- [ ] Add item to wishlist when button is used
- [ ] Add wishlist section to profile page
- [ ] Add to cart button from wishlist
