### ISSUE TITLE
USER STORY: Privacy/Cookie Policy

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#25]
As a **site admin** I can **create a privacy/cookie policy** so that **my website can comply with GDPR guidelines**

### Acceptance Criteria

- [x] Privacy policy
- [x] Link in footer

### Tasks

- [x] Create privacy policy
- [x] Link privacy policy to footer
