### ISSUE TITLE
USER STORY: Click and Collect

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#26]
As a **site user** I can **opt for click and collect** so that **I can quickly collect my items and avoid shipping fees**

### Acceptance Criteria

- [ ] Click and collect option in checkout
- [ ] No shipping fees for any product
- [ ] Give collection time estimate before order complete
- [ ] Confirm collection time and address in order confirmation email

### Tasks

- [ ] Create click and collect option in checkout
- [ ] Remove shipping fee when click and collect selected
- [ ] Give collection time estimate and address

**Comment by alexkavanagh-dev** [comment]
This feature will not be added in the final version.
