### ISSUE TITLE
USER STORY: Free Delivery

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#28]
As a **site admin** I can **add a free delivery cutoff price** so that **at a cart total cutoff price I can offer free shipping to entice customers to spend more**

### Acceptance Criteria

- [x] Free shipping after 60
- [x] Flat 7.50 shipping fee otherwise

### Tasks

- [x] Calculate cart total from items
- [x] Use cart total to check if user is over cutoff
- [x] Remove shipping fee if customer is over cutoff
