### ISSUE TITLE
USER STORY: Sale Products

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#3]
As a **site user** I can **see a badge on sale products** so that **I can quickly identify products on special offer**

### Acceptance Criteria

- [ ] Sale badge shows on product cards
- [ ] Badge clearly identifies product as on sale
- [ ] Original price is struck out next to sale price

### Tasks

- [ ] Create sale badge
- [ ] Add function for sale products to automatically have sale badge
