### ISSUE TITLE
USER STORY: Cart Total

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#4]
As a **site user** I can **easily see my cart total across the site** so that **I can be aware of how much I'm spending**

### Acceptance Criteria

- [ ] Show total under cart icon in navbar
- [ ] Total updates along with each new item
- [ ] Can be seen across the website

### Tasks

- [ ] Create shopping cart
- [ ] Add cart icon to navbar
- [ ] Calculate and display cart total under icon
