### ISSUE TITLE
USER STORY: Register an Account

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#5]
As a **site user** I can **register an account** so that **I can view my profile, order history and save my details for future orders**

### Acceptance Criteria

- [ ] User can sign up with email and password
- [ ] Confirmation on signup
- [ ] Sign up link in navbar and footer

### Tasks

- [ ] Create sign up page
- [ ] Install django all auth
- [ ] Use django all auth functions to create ability for account creation
