### ISSUE TITLE
USER STORY: Password Recovery

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#6]
As a **registered user** I can **recover my password** so that **in the event I forget it, I can retrieve access to my account**

### Acceptance Criteria

- [ ] Link to forgot password in login page
- [ ] Use email to verify password reset
- [ ] Require user to enter new password twice and match them

### Tasks

- [ ] Create forgot password page
- [ ] Take user entered email and send an email to verify it is the account owner
- [ ] Link user to password reset page for their account
- [ ] Take inputted new password and apply that to  users account
