### ISSUE TITLE
USER STORY: Product Sorting

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#7]
As a **site user** I can **sort products** so that **I can view products by best rated, pricing, alphabetical etc**

### Acceptance Criteria

- [ ] Sorting by rating, pricing, alphabetical
- [ ] Dropdown menu to select sort by

### Tasks

- [ ] Create dropdown menu of options
- [ ] Take input from menu and sort products by input
