### ISSUE TITLE
USER STORY: Product Categories

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#8]
As a **site user** I can **filter products by category** so that **I can narrow my search down to specific products I'm interested in**

### Acceptance Criteria

- [ ] Filter menu next to sorting menu
- [ ] Filter by multiple products at once

### Tasks

- [ ] Create filter menu
- [ ] Take input from filter menu to filter product list
