### ISSUE TITLE
USER STORY: Search Website

### ISSUE THREAD

**Issue by alexkavanagh-dev** [alexkavanagh-dev/the-salon-ecommerce#9]
As a **site user** I can **search the website** so that **I can quickly look for specific products I want**

### Acceptance Criteria

- [ ] Search bar in navbar
- [ ] Search both title and descriptions of products
- [ ] Search results display on their own page

### Tasks

- [ ] Create search bar in navbar
- [ ] Take query from search bar on submission
- [ ] Use query to filter database
- [ ] Display filtered results on their own page
